AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Description: A slack slash command to list stacks of AWS CloudFormation

Resources:
  ListCfnStacks:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: list-cfn-stacks
      Runtime: go1.x
      Timeout: 10
      CodeUri: src/
      Handler: list-cfn-stacks
      Role: arn:aws:iam::your-account-id:role/your-role-name
      Events:
        ListCfnStacksTrigger:
          Type: Api
          Properties:
            Path: /
            Method: post
